# Generated by Django 5.1.1 on 2024-10-06 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visual_model', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suspiciousactivity',
            name='screenshot',
            field=models.ImageField(upload_to='static/suspicious_activities/'),
        ),
    ]
