# Generated by Django 5.1.1 on 2024-10-06 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('visual_model', '0002_alter_suspiciousactivity_screenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='suspiciousactivity',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.student'),
        ),
    ]
